from .audio_mood_analyzer import NODE_CLASS_MAPPINGS as _A, NODE_DISPLAY_NAME_MAPPINGS as _DA
from .mood_json_nodes import NODE_CLASS_MAPPINGS as _B, NODE_DISPLAY_NAME_MAPPINGS as _DB

NODE_CLASS_MAPPINGS = {**_A, **_B}
NODE_DISPLAY_NAME_MAPPINGS = {**_DA, **_DB}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
